### ISSUE TITLE
Non riesco a fare push

### ISSUE THREAD

**Issue by Glonor** [ict4g/ase2017#10]
$ git push origin master
remote: Permission to ict4g/ase2017.git denied to Glonor.
fatal: unable to access 'https://github.com/ict4g/ase2017.git/': The requested URL returned error: 403

**Comment by avillafiorita** [comment]
github ha un meccanismo di controllo accessi piu' esteso di quello 
fornito da Git, in modo da consentire contributi da "estranei".

- il meccanismo: clone, commit, push funziona per tutti i profili a cui 
e' stato garantito accesso (nel caso di ase2017: adolfo, aaron)

- e' comunque possibile contribuire al repository in questo modo:

     - fork del repository

     - commit

     - pull request

(https://help.github.com/articles/about-pull-requests/)

chiudo la issue, perche' e' il comportamento inteso.
